FROM node:20-slim
RUN npm install -g pnpm@8.15.4
WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml tsconfig.json ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

EXPOSE ${PORT}

CMD ["sh", "-c", "pnpm migration:generate && pnpm migration:push && node build/src/index.js"]