export const codeFileExtensions: any = {
  js: "JavaScript",
  jsx: "JavaScript XML",
  ts: "TypeScript",
  tsx: "TypeScript XML",
  py: "Python",
  tsc: "TypeScript Config",
  java: "Java",
  class: "Java Class File",
  jar: "Java Archive",
  cpp: "C++",
  c: "C",
  h: "C Header File",
  cs: "C#",
  fs: "F#",
  vb: "Visual Basic",
  go: "Go",
  rb: "Ruby",
  php: "PHP: Hypertext Preprocessor",
  sql: "Structured Query Language",
  swift: "Swift",
  kt: "Kotlin",
  dart: "Dart",
  scala: "Scala",
  rs: "Rust",
  lua: "Lua",
  pl: "Perl",
  pm: "Perl Module",
  asm: "Assembly Language",
  r: "R",
  sh: "Shell Script",
  bash: "Bash Script",
  zsh: "Z Shell Script",
  fish: "Fish Shell Script",
  bat: "Batch File",
  ps1: "PowerShell Script",
  md: "Markdown",
  json: "JavaScript Object Notation",
  yaml: "YAML Ain't Markup Language",
  yml: "YAML Ain't Markup Language",
  ini: "Initialization File",
  log: "Log File",
  env: "Environment File",
  xml: "Extensible Markup Language",
  html: "HyperText Markup Language",
  css: "Cascading Style Sheets",
  sass: "Syntactically Awesome Stylesheets",
  scss: "Sassy CSS",
  less: "Leaner CSS",
  tex: "LaTeX",
  tsconfig: "TypeScript Config",
  xsl: "Extensible Stylesheet Language",
  svg: "Scalable Vector Graphics",
  plist: "Property List",
  cfg: "Configuration File",
  toml: "Tom's Obvious Minimal Language",
  wsdl: "Web Services Description Language",
  xsd: "XML Schema Definition",
  lock: "Lock File",
  map: "Source Map",
  vbs: "VBScript",
  ipynb: "Jupyter Notebook",
  coffee: "CoffeeScript",
  ice: "Ice Protocol Definition",
  thrift: "Thrift Interface Definition",
  proto: "Protocol Buffers",
  groovy: "Groovy Script",
  gvy: "Groovy Script",
  gy: "Groovy Script",
  gsh: "Groovy Shell Script",
  as: "ActionScript",
  m: "Objective-C",
  mm: "Objective-C++",
  qml: "Qt Markup Language",
  hpp: "C++ Header File",
  hxx: "C++ Header File",
  cc: "C++ Source File",
  vala: "Vala Source File",
  pas: "Pascal Source File",
  d: "D Source File",
  nim: "Nim Source File",
  ejs: "Embedded JavaScript",
  handlebars: "Handlebars Template",
  hbs: "Handlebars Template",
  liquid: "Liquid Template",
  erb: "Embedded Ruby",
  twig: "Twig Template",
  mustache: "Mustache Template",
  pug: "Pug Template",
  jade: "Jade Template",
  clj: "Clojure",
  edn: "Clojure Data",
  ex: "Elixir",
  exs: "Elixir Script",
  erl: "Erlang",
  hrl: "Erlang Header",
  xq: "XQuery",
  xquery: "XQuery",
  xslt: "XSLT Stylesheet",
  gml: "GameMaker Language",
  gd: "Godot Script",
  vrx: "VR Script",
  tsql: "T-SQL",
  prc: "Oracle Procedure",
  adoc: "AsciiDoc",
  rst: "reStructuredText",
};
